name: Build image and publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::926646707128:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS
        #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
      
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
      
    - name: Build images
      env:
        ECR_REGISTRY: public.ecr.aws/u9v8s8j7
        IMAGE_TAG: latest
      run: |
        docker build --file net-lama/Dockerfile --tag $ECR_REGISTRY/net-lama:$IMAGE_TAG ./net-lama
        #docker build --file networktest/Dockerfile --tag $ECR_REGISTRY/networktest:$IMAGE_TAG ./networktest

    - name: Push images to AWS ECR
      id: build-image
      env:
        ECR_REGISTRY: public.ecr.aws/u9v8s8j7
        IMAGE_TAG: latest
      run: |
        docker push $ECR_REGISTRY/net-lama:$IMAGE_TAG
        #docker push $ECR_REGISTRY/networktest:$IMAGE_TAG

