name: Build image and publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code
      
    - name: Build the Docker image for net-lama
      #run: docker build --file net-lama/Dockerfile --tag fox27374/net-lama:latest ./net-lama
      run: docker build --file net-lama/Dockerfile --tag net-lama:latest ./net-lama
      
    - name: Build the Docker image for networktest
      #run: docker build --file networktest/Dockerfile --tag fox27374/networktest:latest ./networktest
      run: docker build --file networktest/Dockerfile --tag networktest:latest ./networktest
      
#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-west-1
        image: net-lama:latest, networktest:latest
        
    - name: List images
      run: docker image ls
      
    - name: Push net-lama image
      run: docker push fox27374/net-lama:latest
      
    - name: Push networktest image
      run: docker push fox27374/networktest:latest
