name: Build image and publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code
      
    - name: Build the Docker image
      run: docker build --file net-lama/Dockerfile --tag fox27374/net-lama:$(date +%s) ./net-lama
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push the latest Docker image
      run: docker push fox27374/net-lama:latest
